// IPC channel names shared between main and preload. Single source of truth.

export const IPC = {
  // invoke/handle (request -> response)
  scanLan: 'discovery:scan',
  scanCancel: 'discovery:scanCancel',
  refreshInstance: 'discovery:refresh',
  pullModel: 'models:pull',
  pullModelCancel: 'models:pullCancel',
  ollamaStatus: 'ollama:status',
  ollamaDelete: 'ollama:delete',
  ollamaSetLoaded: 'ollama:setLoaded',
  getMcpConfig: 'mcp:getConfig',
  getControlInfo: 'control:info',
  addManualHost: 'hosts:addManual',
  removeManualHost: 'hosts:removeManual',
  getInstances: 'instances:get',
  getSettings: 'settings:get',
  setSettings: 'settings:set',
  listProviderModels: 'settings:listProviderModels',
  validateProviderModels: 'settings:validateProviderModels',
  openExternal: 'sys:openExternal',
  pickFolder: 'project:pickFolder',
  getProjectFolder: 'project:getFolder',
  chatStart: 'chat:start',
  chatCancel: 'chat:cancel',
  orchestratorStart: 'orch:start',
  orchestratorCancel: 'orch:cancel',
  orchestratorAnswer: 'orch:answer',
  readProjectFile: 'orch:readFile',
  historyList: 'history:list',
  historyGet: 'history:get',
  historyDelete: 'history:delete',
  historyClear: 'history:clear',
  historyReadFile: 'history:readFile',
  continuousStart: 'continuous:start',
  continuousStop: 'continuous:stop',
  commandApprove: 'commands:approve',
  commitDiff: 'git:commitDiff',
  jarvisSend: 'jarvis:send',
  notifyTest: 'notify:test',
  openProjectFolder: 'sys:openProjectFolder',
  revealProjectFile: 'sys:revealProjectFile',
  revealHistoryFile: 'sys:revealHistoryFile',
  historyExport: 'history:export',
  // main -> renderer events (webContents.send)
  evtScanProgress: 'evt:scanProgress',
  evtInstances: 'evt:instances',
  evtChatChunk: 'evt:chatChunk',
  evtOrchTurnStart: 'evt:orchTurnStart',
  evtOrchDelta: 'evt:orchDelta',
  evtOrchTurnEnd: 'evt:orchTurnEnd',
  evtOrchDone: 'evt:orchDone',
  evtOrchError: 'evt:orchError',
  evtContCycleStart: 'evt:contCycleStart',
  evtContTurn: 'evt:contTurn',
  evtContCycleEnd: 'evt:contCycleEnd',
  evtContDone: 'evt:contDone',
  evtContError: 'evt:contError',
  evtPullProgress: 'evt:pullProgress',
  evtCommandApprovalRequest: 'evt:commandApprovalRequest',
  evtJarvisReply: 'evt:jarvisReply',
  evtJarvisAction: 'evt:jarvisAction',
  evtOrchestratorAsk: 'evt:orchAsk'
} as const
