// A tiny stand-in for the Ollama HTTP API so the app can be exercised with no real
// Ollama and no Windows. Implements the three endpoints the app uses:
//   GET  /api/version   -> { version }
//   GET  /api/tags      -> { models: [...] }
//   POST /api/chat      -> NDJSON stream of { message: { content }, done }
//
// Usage:
//   npm run mock                 # one instance on 11434
//   npm run mock -- 11434 11435  # simulate two "machines" on different ports
//
// Also exports startMockOllama() for use in tests.

import http from 'node:http'

export interface MockModel {
  name: string
  size?: number
  parameter_size?: string
  quantization_level?: string
}

const DEFAULT_MODELS: MockModel[] = [
  { name: 'qwen2.5-coder:7b', size: 4_700_000_000, parameter_size: '7B', quantization_level: 'Q4_K_M' },
  { name: 'llama3.1:8b', size: 4_900_000_000, parameter_size: '8B', quantization_level: 'Q4_K_M' }
]

/**
 * Produce a role-appropriate canned reply so the orchestrator loop can be exercised
 * end-to-end against the mock. Branches on the system prompt the orchestrator sends.
 */
export function mockReplyFor(messages: { role: string; content: string }[], model: string): string {
  // Match the distinctive "ROLE: X" marker the tuned prompts put in each system prompt.
  // (Reviewer prompt also mentions "the coder", so a bare includes('CODER') would misroute.)
  const system = messages.find((m) => m.role === 'system')?.content.toUpperCase() ?? ''
  const userText = messages
    .filter((m) => m.role === 'user')
    .map((m) => m.content)
    .join('\n')
    .toUpperCase()

  if (system.includes('ROLE: LEAD')) {
    // Count prior cycles from the progress log the lead is given; finish after two.
    const priorCycles = (userText.match(/## CYCLE/g) ?? []).length
    if (priorCycles >= 2) return 'GOAL COMPLETE'
    return `NEXT STEP: implement part ${priorCycles + 1}\nPLAN:\n1. [x] scaffold\n2. flesh out part ${priorCycles + 1}`
  }
  if (system.includes('ROLE: PLANNER')) {
    return '1. Create the main file.\n2. Add a README.\n3. Verify it builds.'
  }
  if (system.includes('ROLE: REVIEWER')) {
    return 'APPROVED'
  }
  if (system.includes('ROLE: CODER')) {
    return [
      'Here are the files:',
      'FILE: hello.txt',
      '```',
      `Hello from ${model}!`,
      'Line two.',
      '```',
      'FILE: src/app.js',
      '```js',
      "console.log('generated by the mock coder')",
      '```'
    ].join('\n')
  }
  return `Hello from the mock ${model}. This is a simulated streamed reply.`
}

export function createMockServer(models: MockModel[] = DEFAULT_MODELS, version = '0.1.0-mock'): http.Server {
  return http.createServer((req, res) => {
    const url = req.url ?? ''

    if (req.method === 'GET' && url.startsWith('/api/version')) {
      res.writeHead(200, { 'Content-Type': 'application/json' })
      res.end(JSON.stringify({ version }))
      return
    }

    if (req.method === 'GET' && url.startsWith('/api/tags')) {
      res.writeHead(200, { 'Content-Type': 'application/json' })
      res.end(
        JSON.stringify({
          models: models.map((m) => ({
            name: m.name,
            size: m.size,
            details: { parameter_size: m.parameter_size, quantization_level: m.quantization_level }
          }))
        })
      )
      return
    }

    if (req.method === 'GET' && url.startsWith('/api/ps')) {
      // Pretend the first model is loaded in memory.
      res.writeHead(200, { 'Content-Type': 'application/json' })
      res.end(JSON.stringify({ models: models.slice(0, 1).map((m) => ({ name: m.name })) }))
      return
    }

    if (req.method === 'POST' && url.startsWith('/api/pull')) {
      let body = ''
      req.on('data', (c) => (body += c))
      req.on('end', () => {
        res.writeHead(200, { 'Content-Type': 'application/x-ndjson' })
        const steps = [
          { status: 'pulling manifest' },
          { status: 'downloading', total: 1000, completed: 400 },
          { status: 'downloading', total: 1000, completed: 1000 },
          { status: 'success' }
        ]
        let i = 0
        const timer = setInterval(() => {
          if (i < steps.length) {
            res.write(JSON.stringify(steps[i]) + '\n')
            i++
          } else {
            clearInterval(timer)
            res.end()
          }
        }, 20)
      })
      return
    }

    if (req.method === 'POST' && url.startsWith('/api/chat')) {
      let body = ''
      req.on('data', (c) => (body += c))
      req.on('end', () => {
        let model = 'mock'
        let reply = `Hello from the mock ${model}. This is a simulated streamed reply.`
        try {
          const parsed = JSON.parse(body) as { model?: string; messages?: { role: string; content: string }[] }
          model = parsed.model ?? model
          reply = mockReplyFor(parsed.messages ?? [], model)
        } catch {
          /* ignore */
        }
        res.writeHead(200, { 'Content-Type': 'application/x-ndjson' })
        // Split on whitespace boundaries but KEEP the separators, so streamed chunks
        // reconstruct the original text exactly (newlines in FILE blocks are preserved).
        const tokens = reply.split(/(\s+)/).filter((t) => t.length > 0)
        let i = 0
        const timer = setInterval(() => {
          if (i < tokens.length) {
            res.write(JSON.stringify({ message: { content: tokens[i] }, done: false }) + '\n')
            i++
          } else {
            res.write(
              JSON.stringify({
                message: { content: '' },
                done: true,
                eval_count: tokens.length,
                eval_duration: 500_000_000, // 0.5s → tokens/0.5 tok/s
                prompt_eval_count: 8,
                total_duration: 700_000_000
              }) + '\n'
            )
            clearInterval(timer)
            res.end()
          }
        }, 15)
      })
      return
    }

    res.writeHead(404)
    res.end()
  })
}

/** Start a mock server on the given port. Resolves once listening. */
export function startMockOllama(port: number, models?: MockModel[]): Promise<http.Server> {
  const server = createMockServer(models)
  return new Promise((resolve) => server.listen(port, '127.0.0.1', () => resolve(server)))
}

// CLI entry: start one server per port argument (default 11434).
const isMain = process.argv[1] && import.meta.url === `file://${process.argv[1]}`
if (isMain) {
  const ports = process.argv.slice(2).map(Number).filter((n) => Number.isInteger(n) && n > 0)
  const chosen = ports.length ? ports : [11434]
  for (const port of chosen) {
    startMockOllama(port).then(() => console.log(`mock-ollama listening on http://127.0.0.1:${port}`))
  }
}
